#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<ctype.h>
#include<unistd.h>

/**
 * /tmp/out: the file is generated by ./save, 
 *           it is a guangyibiao like
 *           (A()())
 * load.c - according to the file to restore the tree
*/

#define FNAME    "/tmp/out"

typedef char score;


typedef struct node_st
{
	score data;
	struct node_st *l, *r;
}tree_node;

/** draw_ - draw the whole tree by recursion, 
 *          draw right, then mid, finally left
 *  @root: the tree
 *  @level: which level to darw
*/
void draw_(tree_node *root, int level)
{
	int i;
	if(NULL == root)
		return;
	if(NULL != root->r){
		draw_(root->r, level + 1);
		for(i=0; i<level; i++)
		{
			printf("  ");
		}
		printf(" /\n");
	}

	for(i=0; i<level; i++)
	{
		printf("  ");
	}
	printf("%c\n",root->data);
	if(NULL != root->l){
		for(i=0; i<level; i++)
		{
			printf("  ");
		}
		printf(" \\\n");
		draw_(root->l, level + 1);
	}
}

void draw(tree_node *root)
{
	draw_(root, 0);
}

tree_node * load_(FILE *fp)
{
	tree_node *root;
	int c;
	c = fgetc(fp);
	if(c != '(')
	{
		fprintf(stderr,"fgetc not (,failed\n");
		exit(1);
	}
	
	c = fgetc(fp);
	if(')' == c){
		return NULL;
	}
	root = malloc(sizeof(*root));
	if(NULL == root)
		exit(1);

	root->data = c;
	root->l = load_(fp);
	root->r = load_(fp);
	c = fgetc(fp);
	if(')' != c){
		fprintf(stderr,"fgetc not ),failed\n");
		exit(1);
	}
	return root;
}

tree_node *load(const char *path)
{
	tree_node *root;
	FILE *fp = fopen(path, "r");
	if(NULL == fp)
		return NULL;

	root = load_(fp);

	fclose(fp);
	return root;
}

int main()
{
	tree_node *root;
	root = load(FNAME);
	draw(root);

	exit(0);
}
