#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<ctype.h>
#include<unistd.h>


/**
 * /tmp/out: the file is generated by ./save, 
 *           it is a guangyibiao like
 *           (A()())
 * save.c - save the tree to file /tmp/out by the 
 *          format of guangyibiao
*/

#define FNAME    "/tmp/out"

typedef char score;

typedef struct node_st
{
	score data;
	struct node_st *l, *r;
}tree_node;

#if 0
void printf_s(score *d)
{
	printf("%d %s %d\n",d->id,d->name,d->math);
}
#else
void printf_s(score *d)
{
	printf("%c\n",*d);
}
#endif
enum travel_mode
{
	PREORDER = 0,  // xianxu 
	INORDER,       // zhongxu
	POSTORDER,     // houxu
	TRAVEL_MODE_BOTTOM
};

void travel(tree_node *root, enum travel_mode mode)
{
	if(mode < PREORDER || mode >=TRAVEL_MODE_BOTTOM){
		return;
	}

	if(root == NULL)
		return;
	if(PREORDER == mode){ printf_s(&root->data);}
	travel(root->l, mode);
	if(INORDER == mode){ printf_s(&root->data);}
	travel(root->r, mode);
	if(POSTORDER == mode){ printf_s(&root->data);}
}

void table(tree_node *root)
{
	printf("(");
	
	if(NULL == root){
		printf(")");
		return;
	}
	printf("%c",root->data);
	
	table(root->l);
	table(root->r);
	printf(")");
	return;
}

/**
 * insert - insert the data to the tree, by recursion
 * bigger to right, others to left
 * @root: pointer to the tree
 * @data: pointer to the data
*/
int insert(tree_node **root, score *data)
{
	tree_node *tmp;
	if(NULL == root || NULL == data)
		return -1;

	if(NULL == *root)
	{
		//printf("insert data %c\n", *data);
		tmp = malloc(sizeof(tree_node));
		if(NULL == tmp)
			return -2;
		tmp->l = NULL;
		tmp->r = NULL;
		memcpy(&tmp->data, data, sizeof(*data));
		*root = tmp;
		return 0;
	}
	else
	{
		if(*data > (*root)->data )
		{
			//printf("right: *data=%c > %c=node_data\n",*data,(*root)->data);
			return insert( &((*root)->r), data);
		}
		else{
			//printf("left: *data=%c > %c=node_data\n",*data,(*root)->data);
			return insert( &((*root)->l), data);
		}
	}
}


void draw_(tree_node *root, int level)
{
	int i;
	if(NULL == root)
		return;
	if(NULL != root->r){
		draw_(root->r, level + 1);
		for(i=0; i<level; i++)
		{
			printf("  ");
		}
		printf(" /\n");
	}

	for(i=0; i<level; i++)
	{
		printf("  ");
	}
	printf_s(&root->data);
	if(NULL != root->l){
		for(i=0; i<level; i++)
		{
			printf("  ");
		}
		printf(" \\\n");
		draw_(root->l, level + 1);
	}
}

void draw(tree_node *root)
{
	draw_(root, 0);
}



int save_(tree_node *root, FILE *fp)
{
	fputc('(',fp);

	if(NULL == root){ // the leaf node
		fputc(')',fp);
		return 0;
	}
	fputc(root->data,fp);
	save_(root->l,fp);
	save_(root->r,fp);
	fputc(')',fp);
	return 0;
}

int save(tree_node *root, const char *path)
{
	FILE *fp = fopen(path,"w");
	if(NULL == fp)
		return -1;

	save_(root,fp);
	
	fclose(fp);
	return 0;
}

int main()
{
	//int arr[] = {1,2,3,7,6,5,4,8,9,0};
	//int arr[] = {1,2,3,7,6,5,9,8,4};
	char arr[] = "cefadjbh";
	int i;
	tree_node *tree = NULL;

	for(i = 0; i < sizeof(arr)/sizeof(*arr)-1;i++)
	{
		insert(&tree, &arr[i]);
	}

	draw(tree);
	table(tree);printf("\n");
	save(tree, FNAME);
	
	exit(0);
}
